import streamlit as st
import pandas as pd
import sqlite3
import plotly.graph_objects as go
import plotly.express as px
import os

# Setting the page configuration - this must be the first Streamlit command in the script
# wide layout gives us more space to display charts and tables
st.set_page_config(
    page_title="AutoNarrative - KPI Intelligence Dashboard",
    page_icon="chart_with_upwards_trend",
    layout="wide"
)

DB_PATH = "data/processed/novatech.db"
NARRATIVES_PATH = "data/processed/narratives.csv"


def load_kpi_data():
    # Load the full KPI dataset from SQLite database
    conn = sqlite3.connect(DB_PATH)
    df = pd.read_sql("SELECT * FROM kpi_data", conn, parse_dates=["date"])
    conn.close()
    return df


def load_narratives():
    # Load the narratives CSV generated by narrative_engine.py
    if os.path.exists(NARRATIVES_PATH):
        df = pd.read_csv(NARRATIVES_PATH, parse_dates=["date"])
        return df
    return pd.DataFrame()


def plot_kpi_with_anomalies(kpi_df, narratives_df, column, title, y_label, color):
    # This function creates a Plotly line chart for a given KPI
    # It overlays red scatter markers on weeks that were flagged as anomalies
    # This visual pattern is standard in production monitoring dashboards

    fig = go.Figure()

    # Add the main KPI line
    fig.add_trace(go.Scatter(
        x=kpi_df["date"],
        y=kpi_df[column],
        mode="lines",
        name=title,
        line=dict(color=color, width=2)
    ))

    # Add the rolling 4 week average line as a reference trend
    if column + "_4w_avg" in kpi_df.columns:
        fig.add_trace(go.Scatter(
            x=kpi_df["date"],
            y=kpi_df[column + "_4w_avg"],
            mode="lines",
            name="4-Week Average",
            line=dict(color="grey", width=1, dash="dot"),
            opacity=0.7
        ))

    # Overlay anomaly markers if narratives data is available
    if len(narratives_df) > 0 and column + "_anomaly" in narratives_df.columns:
        anomaly_weeks = narratives_df[narratives_df[column + "_anomaly"] == True]

        if len(anomaly_weeks) > 0:
            # Merge anomaly weeks with KPI data to get actual values at anomaly dates
            anomaly_points = kpi_df[kpi_df["date"].isin(anomaly_weeks["date"])]

            fig.add_trace(go.Scatter(
                x=anomaly_points["date"],
                y=anomaly_points[column],
                mode="markers",
                name="Anomaly Detected",
                marker=dict(color="red", size=10, symbol="circle-open", line=dict(width=2))
            ))

    # Chart layout styling
    fig.update_layout(
        title=title,
        xaxis_title="Week",
        yaxis_title=y_label,
        hovermode="x unified",
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        height=350,
        margin=dict(l=40, r=40, t=60, b=40),
        plot_bgcolor="white",
        paper_bgcolor="white"
    )

    fig.update_xaxes(showgrid=True, gridcolor="rgba(200,200,200,0.3)")
    fig.update_yaxes(showgrid=True, gridcolor="rgba(200,200,200,0.3)")

    return fig


def render_dashboard():
    # Main dashboard rendering function
    # Streamlit renders components top to bottom in the order they are written

    # Dashboard header section
    st.title("AutoNarrative - KPI Intelligence Dashboard")
    st.markdown("Automated anomaly detection and executive narrative generation for NovaTech Solutions Pvt. Ltd. - a B2B SaaS company based in Bengaluru, India.")
    st.markdown("---")

    # Load data
    kpi_df = load_kpi_data()
    narratives_df = load_narratives()

    # Top level KPI summary metrics row
    # These metric cards give an instant snapshot of the latest week performance
    latest = kpi_df.iloc[-1]
    prev = kpi_df.iloc[-2]

    col1, col2, col3, col4, col5 = st.columns(5)

    with col1:
        revenue_delta = round(((latest["revenue"] - prev["revenue"]) / prev["revenue"]) * 100, 1)
        st.metric(
            label="Latest Revenue",
            value="INR " + "{:,.0f}".format(latest["revenue"]),
            delta=str(revenue_delta) + "% WoW"
        )

    with col2:
        users_delta = int(latest["active_users"] - prev["active_users"])
        st.metric(
            label="Active Users",
            value="{:,}".format(int(latest["active_users"])),
            delta=str(users_delta) + " WoW"
        )

    with col3:
        churn_delta = round((latest["churn_rate"] - prev["churn_rate"]) * 100, 3)
        st.metric(
            label="Churn Rate",
            value=str(round(latest["churn_rate"] * 100, 2)) + "%",
            delta=str(churn_delta) + "% WoW",
            delta_color="inverse"
        )

    with col4:
        cac_delta = round(latest["cac"] - prev["cac"], 1)
        st.metric(
            label="CAC",
            value="INR " + str(round(latest["cac"], 0)),
            delta=str(cac_delta) + " WoW",
            delta_color="inverse"
        )

    with col5:
        st.metric(
            label="Anomalies Detected",
            value=str(len(narratives_df)) + " weeks",
            delta="Across 2 years"
        )

    st.markdown("---")

    # KPI Charts section - two charts per row for clean layout
    st.subheader("KPI Trend Analysis with Anomaly Detection")
    st.caption("Red circles indicate weeks flagged as anomalous by the hybrid Prophet and Z-score detection engine.")

    # First row - Revenue and Active Users
    chart_col1, chart_col2 = st.columns(2)

    with chart_col1:
        fig_revenue = plot_kpi_with_anomalies(
            kpi_df, narratives_df,
            column="revenue",
            title="Weekly Revenue",
            y_label="Revenue (USD)",
            color="#1f77b4"
        )
        st.plotly_chart(fig_revenue, use_container_width=True)

    with chart_col2:
        fig_users = plot_kpi_with_anomalies(
            kpi_df, narratives_df,
            column="active_users",
            title="Active Users",
            y_label="Users",
            color="#2ca02c"
        )
        st.plotly_chart(fig_users, use_container_width=True)

    # Second row - Churn Rate and CAC
    chart_col3, chart_col4 = st.columns(2)

    with chart_col3:
        fig_churn = plot_kpi_with_anomalies(
            kpi_df, narratives_df,
            column="churn_rate",
            title="Churn Rate",
            y_label="Churn Rate",
            color="#d62728"
        )
        st.plotly_chart(fig_churn, use_container_width=True)

    with chart_col4:
        fig_cac = plot_kpi_with_anomalies(
            kpi_df, narratives_df,
            column="cac",
            title="Customer Acquisition Cost",
            y_label="CAC (USD)",
            color="#ff7f0e"
        )
        st.plotly_chart(fig_cac, use_container_width=True)

    st.markdown("---")

    # Anomaly Narratives section
    # This is the core differentiator of the project - showing LLM generated narratives
    st.subheader("Automated Executive Narratives")
    st.caption("Each narrative was automatically generated by an LLM using the anomaly context and surrounding business metrics.")

    if len(narratives_df) > 0:
        for index, row in narratives_df.iterrows():
            date_str = pd.to_datetime(row["date"]).strftime("%B %d, %Y")

            # Each narrative is displayed inside an expandable section
            # Collapsed by default so the page is not overwhelming on first load
            with st.expander("Week of " + date_str + " - Click to read narrative"):

                # Show which KPIs were anomalous for this week
                flag_col1, flag_col2, flag_col3 = st.columns(3)

                with flag_col1:
                    if row["revenue_anomaly"]:
                        st.error("Revenue Anomaly Detected")
                    else:
                        st.success("Revenue Normal")

                with flag_col2:
                    if row["active_users_anomaly"]:
                        st.error("Users Anomaly Detected")
                    else:
                        st.success("Users Normal")

                with flag_col3:
                    if row["churn_rate_anomaly"]:
                        st.error("Churn Anomaly Detected")
                    else:
                        st.success("Churn Normal")

                st.markdown("**Executive Narrative:**")
                # Display the narrative in a highlighted info box
                st.info(str(row["narrative"]))

                # Show raw metrics for that week in a small table
                st.markdown("**Week Metrics:**")
                metrics_data = {
                    "Metric": ["Revenue", "Active Users", "Churn Rate"],
                    "Value": [
                        "INR " + "{:,.0f}".format(row["revenue"]),
                        "{:,}".format(int(row["active_users"])),
                        str(round(row["churn_rate"] * 100, 2)) + "%"
                    ]
                }
                st.table(pd.DataFrame(metrics_data))
    else:
        st.warning("No narratives found. Run narrative_engine.py first.")

    st.markdown("---")

    # Raw data table section at the bottom for data transparency
    st.subheader("Full KPI Dataset")
    st.caption("Complete 2-year weekly dataset for NovaTech Solutions.")

    # Format columns for display before showing the table
    display_df = kpi_df[["date", "revenue", "active_users", "churn_rate", "cac", "conversion_rate"]].copy()
    display_df["date"] = display_df["date"].dt.strftime("%Y-%m-%d")
    display_df["revenue"] = display_df["revenue"].apply(lambda x: "$" + "{:,.0f}".format(x))
    display_df["churn_rate"] = display_df["churn_rate"].apply(lambda x: str(round(x * 100, 2)) + "%")
    display_df["conversion_rate"] = display_df["conversion_rate"].apply(lambda x: str(round(x * 100, 2)) + "%")

    st.dataframe(
        display_df,
        use_container_width=True,
        hide_index=True,
        column_config={
            "date": st.column_config.TextColumn("Week Date"),
            "revenue": st.column_config.TextColumn("Revenue (INR)"),
            "active_users": st.column_config.TextColumn("Active Users"),
            "churn_rate": st.column_config.TextColumn("Churn Rate"),
            "cac": st.column_config.NumberColumn("CAC (INR)", format="INR %.0f"),
            "conversion_rate": st.column_config.TextColumn("Conversion Rate"),
        }
    )


if __name__ == "__main__":
    render_dashboard()
