import pandas as pd
import numpy as np
import sqlite3
import os
import logging
from datetime import datetime

# Setting up logging so every action is recorded in a log file inside the logs folder
# This is a standard industry practice for tracking what happened and when
logging.basicConfig(
    filename="logs/autonarrative.log",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

# We are using SQLite because it requires no server setup
# In a real enterprise setting this would be PostgreSQL or Snowflake
DB_PATH = "data/processed/novatech.db"
RAW_DATA_PATH = "data/raw/novatech_kpi.csv"

def load_raw_data(filepath):
    # Load the raw CSV file generated by data_generator.py
    # We parse the date column explicitly so pandas treats it as datetime not string
    df = pd.read_csv(filepath, parse_dates=["date"])
    logging.info("Raw data loaded successfully with " + str(len(df)) + " records")
    print("Raw data loaded:", len(df), "records")
    return df

def validate_data(df):
    # This function checks the data quality before storing it
    # In production this step prevents bad data from corrupting downstream models
    
    errors = []

    # Check 1 - Make sure none of the critical columns are missing
    required_columns = ["date", "revenue", "active_users", "churn_rate", "cac", "conversion_rate"]
    for col in required_columns:
        if col not in df.columns:
            errors.append("Missing required column: " + col)

    # Check 2 - Make sure there are no null values in critical columns
    null_counts = df[required_columns].isnull().sum()
    for col, count in null_counts.items():
        if count > 0:
            errors.append("Column " + col + " has " + str(count) + " null values")

    # Check 3 - Revenue should never be negative
    if (df["revenue"] < 0).any():
        errors.append("Negative values found in revenue column")

    # Check 4 - Active users should always be a positive number
    if (df["active_users"] <= 0).any():
        errors.append("Zero or negative values found in active_users column")

    # Check 5 - Churn rate should be between 0 and 1 since it is a percentage
    if ((df["churn_rate"] < 0) | (df["churn_rate"] > 1)).any():
        errors.append("Churn rate values are outside the valid range of 0 to 1")

    # Check 6 - Conversion rate should be between 0 and 1
    if ((df["conversion_rate"] < 0) | (df["conversion_rate"] > 1)).any():
        errors.append("Conversion rate values are outside the valid range of 0 to 1")

    # If any errors were found, log them and raise an exception to stop the pipeline
    if errors:
        for error in errors:
            logging.error("Validation error: " + error)
        raise ValueError("Data validation failed with " + str(len(errors)) + " errors: " + str(errors))

    # If no errors found, log success and continue
    logging.info("Data validation passed with no errors")
    print("Data validation passed - all checks clear")
    return df

def add_derived_columns(df):
    # This function adds calculated columns that will be useful for anomaly detection later
    
    # Week over week revenue change in percentage
    # This tells us how much revenue changed compared to the previous week
    df["revenue_wow_pct"] = df["revenue"].pct_change() * 100

    # Rolling 4 week average of revenue to understand the short term trend
    # We use this as a baseline to compare current week against recent trend
    df["revenue_4w_avg"] = df["revenue"].rolling(window=4).mean()

    # Rolling 4 week average of active users
    df["users_4w_avg"] = df["active_users"].rolling(window=4).mean()

    # Revenue per active user - this is a key business efficiency metric
    df["revenue_per_user"] = df["revenue"] / df["active_users"]

    # Adding a processed timestamp so we know when this data was last ingested
    df["ingested_at"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    logging.info("Derived columns added successfully")
    print("Derived columns added: revenue_wow_pct, revenue_4w_avg, users_4w_avg, revenue_per_user")
    return df

def store_to_sqlite(df, db_path):
    # Create the processed folder if it does not already exist
    os.makedirs(os.path.dirname(db_path), exist_ok=True)

    # Connect to SQLite database - it will be created automatically if it does not exist
    conn = sqlite3.connect(db_path)

    # Store the dataframe as a table called kpi_data
    # if_exists replace means we overwrite the table every time we ingest fresh data
    df.to_sql("kpi_data", conn, if_exists="replace", index=False)

    # Close the connection after storing
    conn.close()

    logging.info("Data stored to SQLite at " + db_path)
    print("Data stored to SQLite database at:", db_path)
    print("Total records saved:", len(df))

def run_ingestion():
    # This is the master function that runs all ingestion steps in order
    # Step 1 - Load raw CSV
    df = load_raw_data(RAW_DATA_PATH)
    
    # Step 2 - Validate data quality
    df = validate_data(df)
    
    # Step 3 - Add derived/calculated columns
    df = add_derived_columns(df)
    
    # Step 4 - Store clean data to SQLite
    store_to_sqlite(df, DB_PATH)
    
    print("Ingestion pipeline completed successfully")
    return df

if __name__ == "__main__":
    run_ingestion()
