import pandas as pd
import os
import logging
from datetime import datetime
from fpdf import FPDF

# Setting up logging consistent with the rest of the pipeline
logging.basicConfig(
    filename="logs/autonarrative.log",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

NARRATIVES_PATH = "data/processed/narratives.csv"
REPORTS_FOLDER = "reports"


class KPIReport(FPDF):
    # This class extends the FPDF base class to add custom header and footer
    # to every page of our PDF report automatically

    def header(self):
        # Company name on the left side of header
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(30, 30, 30)
        self.cell(100, 10, "NovaTech Solutions", ln=False)

        # Report title on the right side of header
        self.set_font("Helvetica", "", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, "Weekly KPI Anomaly Report", ln=True, align="R")

        # Draw a horizontal line below the header to separate it from content
        self.set_draw_color(200, 200, 200)
        self.line(10, 20, 200, 20)
        self.ln(8)

    def footer(self):
        # Position footer 15mm from the bottom of the page
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)

        # Generated date on the left side of footer
        self.cell(100, 10, "Generated on " + datetime.now().strftime("%B %d, %Y"), ln=False)

        # Page number on the right side of footer
        self.cell(0, 10, "Page " + str(self.page_no()), align="R")


def add_cover_page(pdf, report_date):
    # This function creates the cover page of the report
    # A professional cover page immediately signals production quality to anyone reviewing it

    pdf.add_page()

    # Add top spacing
    pdf.ln(40)

    # Main report title in large bold font
    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(20, 60, 120)
    pdf.cell(0, 15, "AutoNarrative", ln=True, align="C")

    # Subtitle
    pdf.set_font("Helvetica", "", 16)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 10, "Automated KPI Intelligence Report", ln=True, align="C")

    pdf.ln(10)

    # Draw a decorative separator line
    pdf.set_draw_color(20, 60, 120)
    pdf.set_line_width(0.8)
    pdf.line(50, pdf.get_y(), 160, pdf.get_y())
    pdf.set_line_width(0.2)

    pdf.ln(15)

    # Company name
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, "NovaTech Solutions", ln=True, align="C")

    pdf.ln(5)

    # Report generation date
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, "Report Generated: " + datetime.now().strftime("%B %d, %Y"), ln=True, align="C")

    pdf.ln(5)

    # Number of anomalies covered in this report
    pdf.cell(0, 8, "Anomalies Analysed: " + str(report_date), ln=True, align="C")

    pdf.ln(20)

    # Disclaimer at the bottom of cover page
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(
        0, 6,
        "This report was automatically generated by AutoNarrative, an intelligent KPI monitoring "
        "system. Anomalies were detected using a hybrid Prophet and Z-score statistical engine. "
        "Narratives were generated using large language model technology.",
        align="C"
    )


def add_summary_table(pdf, narratives_df):
    # This function adds a summary table showing all anomalous weeks at a glance
    # A summary table helps executives quickly scan the full picture before reading details

    pdf.add_page()

    # Section title
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(20, 60, 120)
    pdf.cell(0, 10, "Executive Summary - Anomaly Overview", ln=True)
    pdf.ln(4)

    # Table column headers with blue background
    pdf.set_fill_color(20, 60, 120)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 9)

    # Define column widths for the table
    col_widths = [35, 35, 30, 30, 30, 30]
    headers = ["Week", "Revenue ($)", "Active Users", "Churn Rate", "Rev Anomaly", "User Anomaly"]

    for i, header in enumerate(headers):
        pdf.cell(col_widths[i], 8, header, border=1, fill=True, align="C")
    pdf.ln()

    # Table data rows alternating between white and light grey background
    pdf.set_font("Helvetica", "", 8)

    for row_index, row in narratives_df.iterrows():
        # Alternate row colors for readability
        if row_index % 2 == 0:
            pdf.set_fill_color(245, 245, 245)
        else:
            pdf.set_fill_color(255, 255, 255)

        pdf.set_text_color(30, 30, 30)

        # Format each cell value for display
        date_str = pd.to_datetime(row["date"]).strftime("%b %d, %Y")
        revenue_str = "INR " + "{:,.0f}".format(row["revenue"])
        users_str = "{:,}".format(int(row["active_users"]))
        churn_str = str(round(row["churn_rate"] * 100, 2)) + "%"
        rev_anomaly_str = "YES" if row["revenue_anomaly"] else "NO"
        user_anomaly_str = "YES" if row["active_users_anomaly"] else "NO"

        row_data = [date_str, revenue_str, users_str, churn_str, rev_anomaly_str, user_anomaly_str]

        for i, value in enumerate(row_data):
            pdf.cell(col_widths[i], 7, value, border=1, fill=True, align="C")
        pdf.ln()

    logging.info("Summary table added to PDF report")


def add_narrative_pages(pdf, narratives_df):
    # This function adds one detailed page per anomalous week
    # Each page shows the KPI metrics and the LLM-generated narrative for that week

    for row_index, row in narratives_df.iterrows():
        pdf.add_page()

        date_str = pd.to_datetime(row["date"]).strftime("%B %d, %Y")

        # Page title with the week date
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(20, 60, 120)
        pdf.cell(0, 10, "Anomaly Report - Week of " + date_str, ln=True)

        # Draw a separator line below the title
        pdf.set_draw_color(200, 200, 200)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(6)

        # KPI metrics section header
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 8, "Key Performance Indicators", ln=True)
        pdf.ln(2)

        # Display each KPI in a clean two column layout
        # Left column is the KPI name, right column is the value
        kpis = [
            ("Revenue", "INR " + "{:,.0f}".format(row["revenue"])),
            ("Active Users", "{:,}".format(int(row["active_users"]))),
            ("Churn Rate", str(round(row["churn_rate"] * 100, 2)) + "%"),
            ("Revenue Anomaly Flagged", "YES" if row["revenue_anomaly"] else "NO"),
            ("Active Users Anomaly Flagged", "YES" if row["active_users_anomaly"] else "NO"),
            ("Churn Rate Anomaly Flagged", "YES" if row["churn_rate_anomaly"] else "NO"),
        ]

        pdf.set_font("Helvetica", "", 10)

        for kpi_name, kpi_value in kpis:
            # Light grey background for each KPI row
            pdf.set_fill_color(245, 247, 250)
            pdf.set_text_color(80, 80, 80)
            pdf.cell(80, 7, kpi_name, border=0, fill=True)
            pdf.set_text_color(20, 20, 20)
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 7, kpi_value, ln=True, fill=False)
            pdf.set_font("Helvetica", "", 10)
            pdf.ln(1)

        pdf.ln(6)

        # Executive narrative section header
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 8, "Executive Narrative", ln=True)

        # Draw a light blue background box behind the narrative text
        pdf.set_fill_color(240, 245, 255)
        pdf.set_draw_color(180, 200, 240)

        # Use multi_cell so long narrative text wraps correctly inside the box
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(30, 30, 30)
        pdf.multi_cell(0, 7, str(row["narrative"]), border=1, fill=True)

        logging.info("Narrative page added for week " + str(row["date"]))


def generate_pdf_report():
    # Load the narratives CSV generated by narrative_engine.py
    narratives_df = pd.read_csv(NARRATIVES_PATH, parse_dates=["date"])

    print("Generating PDF report for", len(narratives_df), "anomalous weeks")

    # Create the KPIReport PDF object
    # We use portrait orientation and A4 page size which is standard for business reports
    pdf = KPIReport(orientation="P", unit="mm", format="A4")

    # Set document metadata that appears in PDF properties
    pdf.set_title("AutoNarrative KPI Report - NovaTech Solutions")
    pdf.set_author("AutoNarrative System")

    # Set default margins for all pages
    pdf.set_margins(10, 25, 10)
    pdf.set_auto_page_break(auto=True, margin=20)

    # Step 1 - Add the cover page
    add_cover_page(pdf, len(narratives_df))

    # Step 2 - Add the executive summary table
    add_summary_table(pdf, narratives_df)

    # Step 3 - Add one detailed page per anomalous week
    add_narrative_pages(pdf, narratives_df)

    # Create reports folder if it does not exist
    os.makedirs(REPORTS_FOLDER, exist_ok=True)

    # Save the PDF with a timestamped filename so each run produces a unique report
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_path = os.path.join(REPORTS_FOLDER, "autonarrative_report_" + timestamp + ".pdf")

    pdf.output(output_path)

    print("PDF report generated successfully at:", output_path)
    print("Total pages:", pdf.page)
    logging.info("PDF report saved to " + output_path)

    return output_path


if __name__ == "__main__":
    report_path = generate_pdf_report()
    print("Report saved to:", report_path)
